### ISSUE TITLE
Prepared statements are never closed

### ISSUE THREAD

**Issue by bigardone** [elixir-ecto/myxql#80] opened 2019-10-04 08:17 UTC
Hi! 👋 

This issue is related to https://github.com/elixir-ecto/myxql/issues/37 and https://github.com/xerions/mariaex/issues/182.

I'm using `0.2.9` and `mysql_global_status_prepared_stmt_count` keeps growing until it reaches the limit and starts raising `MyXQL.Error: (1461) (ER_MAX_PREPARED_STMT_COUNT_REACHED) Can't create more than max_prepared_stmt_count statements (current value: 16382)` errors.

This is how it increases over time, with `prepare: :unnamed` enabled:

![image](https://user-images.githubusercontent.com/1090272/66191103-d2a02a80-e68d-11e9-8542-b2d2250b79c6.png)

On the other hand, a similar service running the same number of instances and using `mariaex` does not have the same issue, always staying around 2.2K:

![image](https://user-images.githubusercontent.com/1090272/66191166-fd8a7e80-e68d-11e9-8e64-25e92e93a5ab.png)

Is this happening to anyone else?

Thanks in advance 🙌

**Comment by wojtekmach** [comment] 2019-10-04 08:50
Thank you for the report.

> ** (Mariaex.Error) (1461): Can't create more than max_prepared_stmt_count statements (current value: 16382)

the error mentions Mariaex, that's a bad copy-paste, right? :)

> This is how it increases over time, with prepare: :unnamed enabled:

This is really weird, enabling this option should make it so we close the statement after executing it. I cannot reproduce this locally.

Any chance you know which statements are leaking and how you execute them (`Repo.all` or `Repo.query` or using the driver directly)? Just to get this out of the way, could you please double-check if you're using the latest myxql version and setting `prepare: :unnamed` in your repo config?

**Comment by wojtekmach** [comment] 2019-10-04 09:12
One more thing regarding the `ER_MAX_PREPARED_STMT_COUNT_REACHED` error. How often do you see this error? Because we actually have code to handle this [1], when we detect this error we disconnect the connection and re-connect, which you should see as `[error] MyXQL.Connection (#PID<0.253.0>) disconnected` and a drop in statements count. So yeah, just wondering if that mechanism is working for you as expected or if there are any issues with it?

[1] https://hexdocs.pm/myxql/MyXQL.html#start_link/1-disconnecting-on-errors

**Comment by bigardone** [comment] 2019-10-04 09:54
> the error mentions Mariaex, that's a bad copy-paste, right? :)

@wojtekmach yeah, copy-paste error, sorry :)

> Any chance you know which statements are leaking and how you execute them (Repo.all or Repo.query or using the driver directly)? 

For the most part, I always use Ecto's query API, like:

```elixir
    from(f in Foo,
      where: f.id == ^id,
      join: b in assoc(f, :bars),
      preload: [bars: b]
    )
    |> Repo.one()

# Or...

    Bar
    |> where_inserted_at_between(from, to)
    |> where_foo_id(foo_id)
    |> Repo.all()
```


I'm also using `Ecto.Multi` to insert `Foo` and its nested `bars`, nothing too complex I reckon.

> One more thing regarding the ER_MAX_PREPARED_STMT_COUNT_REACHED error. How often do you see this error?

It happens when `mysql_global_status_prepared_stmt_count` reaches the max, and this is the log: 

```
[error] MyXQL.Connection (#PID<0.2783.0>) disconnected: ** (MyXQL.Error) (1461) (ER_MAX_PREPARED_STMT_COUNT_REACHED) Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

However, the number of `mysql_global_status_prepared_stmt_count` doesn't seem to increase. BTW, I'm running 3 instances with a connection pool of 20 on each, it that helps.

> could you please double-check if you're using the latest myxql version and setting prepare: :unnamed in your repo config?

Sure:

```
 "myxql": {:hex, :myxql, "0.2.9", "2e26497ab806a4fcba412fade17c43b39d25a69240722a2558aceab9b87b2c4c", [:mix], [{:db_connection, "~> 2.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.6", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm"},
```

```elixir
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.MyXQL,
  database: {:system, "MYSQL_DBNAME"},
  username: {:system, "MYSQL_USERNAME"},
  password: {:system, "MYSQL_PASSWORD"},
  hostname: {:system, "MYSQL_HOST"},
  port: {:system, "MYSQL_PORT", type: :integer},
  pool_size: {:system, "MYSQL_POOL_SIZE", type: :integer},
  timeout: {:system, "MYSQL_TIMEOUT", type: :integer},
  prepare: :unnamed
```

I'm also using [Scrivener](https://github.com/drewolson/scrivener_ecto/blob/master/lib/scrivener/paginater/ecto/query.ex) to paginate the results.

**Comment by wojtekmach** [comment] 2019-10-04 10:02
> It happens when mysql_global_status_prepared_stmt_count reaches the max, and this is the log:

What I meant to ask is does it happen every 5min or 1h etc?

> [error] MyXQL.Connection (#PID<0.2783.0>) disconnected: ** (MyXQL.Error) (1461) (ER_MAX_PREPARED_STMT_COUNT_REACHED) Can't create more than max_prepared_stmt_count statements (current value: 16382)

👍 

> However, the number of mysql_global_status_prepared_stmt_count doesn't seem to increase. 

Any chance you meant to say "doesn't seem to decrease"? :)

What's your server version? Anything worth mentioning about your infrastructure? Do you use ProxySQL for example?

Anyhow, it does seem like myxql bug since you mentioned it works as expected on mariaex.

**Comment by bigardone** [comment] 2019-10-08 07:34
👋 Hi again, and sorry for the late response.
I have been doing some testing, and I have finally found what is creating this huge of prepared statements that don't get closed.

The application can process CSV files uploaded by the users and perform updates on existing records according to the file rows, which may vary from 1000 to 3000 lines.

The process looks something like this:

```elixir
    path
    |> File.stream!()
    |> Parser.parse_stream() # Nimble CSV parser
    |> Stream.map(&process_bar/1)
    |> Stream.reject(&(&1 == nil))
    |> Stream.uniq()
    |> Stream.each(&update_foo/1)
    |> Stream.run()
```

`process_bar` just updates a child `Bar` item, returning its parent `foo_id` and `update_foo` updates every `Foo` parent corresponding to these `foo_ids`.

Every time a file is processed, there is a significant increase 

![image](https://user-images.githubusercontent.com/1090272/66375592-0e98ff80-e9ae-11e9-9fb1-61e0e962bd87.png)

Is it possible that for whatever reason, using streams does not close prepared statements properly?

**Comment by hkrutzer** [comment] 2019-10-09 09:28
We made the issue referenced in OP https://github.com/xerions/mariaex/issues/182 and just switched to MyXQL, and are experiencing this/the same problem again. The description of our setup in that issue is still valid (except twice there's as many tenants).

**Comment by bigardone** [comment] 2019-10-14 13:21
@hkrutzer could you provide more details 🙏 ?

**Comment by hkrutzer** [comment] 2019-10-17 18:33
Today we did a second attempt to deploy to our staging environment. After some time we hit the ol' `ER_MAX_PREPARED_STMT_COUNT_REACHED` again, meaning we had to revert. I still have not been able to reproduce this locally. 

I did investigate the network traffic to MySQL with Wireshark on my local machine, and this shows prepared statements are being closed properly. I also investigated our current patched Mariaex driver, and this one does not close prepared statements, but it re-uses a single prepared statement identifier. MySQL de-allocates the old prepared statement automatically when this happens.

@bigardone perhaps you could try looking at MySQL traffic as well? For me this is not so easy on our staging environment. I used this filter:
```!(frame[60:1] == 0e) and mysql```

**Comment by hkrutzer** [comment] 2019-10-19 16:40
I believe multiple statements are being opened, before the old ones are closed:
![EA82A61E-DC18-4D67-B2AD-668E87669269](https://user-images.githubusercontent.com/3464899/67148434-d774f900-f29f-11e9-9da0-7e05412d1a06.png)

**Comment by hkrutzer** [comment] 2019-10-19 22:40
Doing `insert_or_update` ends up in the `reprepare` code path. This triggers a new prepare and the old one is not cleaned up.

**Comment by hkrutzer** [comment] 2019-10-21 10:12
@wojtekmach it looks like some queries are never cached: https://github.com/elixir-ecto/myxql/blob/eb4fc0c/lib/myxql/connection.ex#L415 but the code still checks whether they are cached, and because they're not they get reprepared: https://github.com/elixir-ecto/myxql/blob/eb4fc0c/lib/myxql/connection.ex#L479. Is there a reason for never caching these queries?

**Comment by wojtekmach** [comment] 2019-10-21 10:23
> Doing insert_or_update ends up in the reprepare code path. This triggers a new prepare and the old one is not cleaned up.

just to be clear, are you using `preparer: :unnamed`?

> it looks like some queries are never cached:

As in the mentioned mariaex issue in the beginning of the thread, the idea was that if a query is not supposed to be cached we'd close it after executing it as not to reach the maximum statement count.

> but the code still checks whether they are cached, and because they're not they get reprepared

besides improving performance (e.g. just executing without preparing), query cache has another important reason to exist and that prepared queries are connection specific. Thus is may be that you checkout one connection, create a query, check out another connection and try executing that query - in that case the query isn't present on that particular connection and needs to be reprepared.

We're still evaluating some options how to move forward with this issue.

**Comment by hkrutzer** [comment] 2019-10-21 10:57
Yes, we are using `prepare: :unnamed`. We have 6 machines connected to MySQL, each with say 50 connections, let's say 200 queries in the application = 6 * 50 * 200 = 60.000 prepared statements, which is too many.

I tried adding
```elixir
defp maybe_reprepare(%Query{cache: :statement} = query, %{prepare: :unnamed} = state) do
    {:ok, query, state}
end
```

as a patch so that we're not leaking prepared statements but it sounds like that is not the right solution. What is the reason for never caching queries with `cache: statement` when `:unnamed` is set?

**Comment by josevalim** [comment] 2019-10-21 11:08
@hkrutzer when `prepare: :unnamed` is used, the close the statement right after, in your case, the maximum amount of open statements you can have at the same time is `6 * 50`.

> What is the reason for never caching queries with cache: statement when :unnamed is set?

What would be the reason to cache any query at all when you have set them to unnamed? :)

**Comment by hkrutzer** [comment] 2019-10-21 11:14
@josevalim 300 is way below our max_prepared_stmt_count of 32768 :)

>What would be the reason to cache any query at all when you have set them to unnamed? :)

Well, queries with `cache: :reference` are *still* cached even when `:unnamed` is set, and therefore don't leak prepared statements.

But queries with `cache: :statement` aren't cached so they always end up being reprepared, regardless of setting `:unnamed`:

```elixir
defp maybe_reprepare(query, state) do
  if cached_query = queries_get(state, query) do
    {:ok, cached_query, state}
  else
    reprepare(query, state)
  end
end
```

and the old prepared statement that was already there doesn't get cleaned up, leading to a leak.

**Comment by hkrutzer** [comment] 2019-10-21 11:23
With `:unnamed` set and a SELECT query:
![image](https://user-images.githubusercontent.com/3464899/67201018-9991e500-f405-11e9-8e55-4308f5851293.png)
one prepared statement, one close

with `:unnamed` set and ding `insert_or_update`:
![image](https://user-images.githubusercontent.com/3464899/67201132-deb61700-f405-11e9-94b6-99f286147929.png)
two prepared statements, one close.

**Comment by wojtekmach** [comment] 2019-10-21 11:32
> with :unnamed set and doing insert_or_update: two prepared statements, one close.

Yes, I'm seeing this behaviour locally too. Thank you.

**Comment by hkrutzer** [comment] 2019-10-22 13:09
@wojtekmach I understand you still want to take some time to design a proper solution, but would you be willing to accept a patch like this:

```patch
diff --git a/lib/myxql/connection.ex b/lib/myxql/connection.ex
index ae3104c93b35d47446fba956c36d242b499f0c87..9e155d48c112f402899b8df154116b7df02c9f77 100644
--- a/lib/myxql/connection.ex
+++ b/lib/myxql/connection.ex
@@ -412,7 +412,6 @@ defmodule MyXQL.Connection do
     end
   end

-  defp queries_put(%{prepare: :unnamed}, %Query{cache: :statement}), do: :ok

   defp queries_put(state, %Query{cache: :statement} = query) do
     try do
@@ -425,7 +424,6 @@ defmodule MyXQL.Connection do
     end
   end

-  defp queries_delete(%{prepare: :unnamed}, %Query{cache: :statement}), do: :ok

   defp queries_delete(state, %Query{} = query) do
     try do
@@ -446,7 +444,6 @@ defmodule MyXQL.Connection do
     end
   end

-  defp queries_get(%{prepare: :unnamed}, %Query{cache: :statement}), do: nil

   defp queries_get(state, %{cache: :statement} = query) do
     try do
```

which will at least improve the situation?

**Comment by wojtekmach** [comment] 2019-10-22 13:44
Hey thanks everyone for help with investigating this bug. I pushed a [fix](https://github.com/elixir-ecto/myxql/commit/9b65b13e05b8bbe10d8ba167cb5d0e31357bd56c), could you try master?

**Comment by bigardone** [comment] 2019-10-23 10:44
@wojtekmach I finally managed to deploy the fix, and now, prepared statements are not increasing that crazy: 

![image](https://user-images.githubusercontent.com/1090272/67385051-97a95c80-f592-11e9-8022-635dbe9a3978.png)


However, we are getting this new error:

```
MyXQL.Error: (1243) (ER_UNKNOWN_STMT_HANDLER) Unknown prepared statement handler (2) given to mysqld_stmt_execute (Most recent call last)
File lib/ecto/adapters/myxql.ex line 211 in Ecto.Adapters.MyXQL.insert/6 (ecto_sql)
File lib/ecto/repo/schema.ex line 651 in Ecto.Repo.Schema.apply/4 (ecto)
File lib/ecto/repo/schema.ex line 262 in anonymous fn/15 in Ecto.Repo.Schema.do_insert/4 (ecto)
File lib/ecto/multi.ex line 579 in Ecto.Multi.apply_operation/5 (ecto)
File lib/enum.ex line 1940 in Enum."-reduce/3-lists^foldl/2-0-"/3 (elixir)
File lib/ecto/multi.ex line 563 in anonymous fn/5 in Ecto.Multi.apply_operations/5 (ecto)
File lib/ecto/adapters/sql.ex line 898 in anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4 (ecto_sql)
File lib/db_connection.ex line 1415 in DBConnection.run_transaction/4 (db_connection)
MyXQL.Error: (1243) (ER_UNKNOWN_STMT_HANDLER) Unknown prepared statement handler (2) given to mysqld_stmt_execute
```

**Comment by hkrutzer** [comment] 2019-10-23 11:07
Deployed this and did not see the error above but had to rollback because of performance degradation. We are also using `Multi` in a few places.

@bigardone did you try with [eb7a16](https://github.com/elixir-ecto/myxql/commit/eb7a161bc1d980a75bb4c2b316adfe7b4073a536) or the commit before? And can you post your exact use of Multi?

**Comment by josevalim** [comment] 2019-10-23 11:26
@hkrutzer which performance degradation?

**Comment by hkrutzer** [comment] 2019-10-23 15:01
My bad, we were actually running this fix:

```patch
diff --git a/lib/myxql/connection.ex b/lib/myxql/connection.ex
index 985f854..ae3104c 100644
--- a/lib/myxql/connection.ex
+++ b/lib/myxql/connection.ex
@@ -475,6 +475,11 @@ defmodule MyXQL.Connection do
     end
   end
 
+  defp maybe_reprepare(%Query{cache: :statement} = query, %{prepare: :unnamed} = state) do
+    {:ok, query, state}
+  end
+
   defp maybe_reprepare(query, state) do
     if cached_query = queries_get(state, query) do
       {:ok, cached_query, state}
```

and not the fix in master. If I try the fix in master, I get failing tests as well with the missing prepared statements. I will try to create a standalone example.

**Comment by josevalim** [comment] 2019-10-25 08:05
Ping @bigardone and @hkrutzer. :)

**Closed** 2019-10-25 09:18 UTC

**Comment by josevalim** [comment] 2019-10-25 09:23
So we have pushed a fix. The fix also standardizes `prepare: :unnamed` to no longer cache any query. This was the documented behaviour all along but we were still caching it for references (but not for statements).

@hkrutzer can you please explain why you are running it with `prepare: :unnamed`?

**Comment by hkrutzer** [comment] 2019-10-28 15:43
@josevalim wrt the performance degradation:
To give some context, we are upgrading from Ecto v2 and a patched Mariaex to Ecto v3 with MyXQL. We synchronize a lot of data each night from some external source. We only see that this synchronization is slower. After some digging and thinking about this, I think that what is happening is our patched Mariaex caches at most 2 queries in the LRU cache, and the syncing repeats a lot of queries so they used to be cached. Now we don't cache any queries, so it's slower. We're going to upgrade anyway and see if we can improve the amount of queries we do.

As to why `prepare: :unnamed`, we have around 900 connections open to a single database instance. If they all do the same ~100 queries we quickly go over the maximum amount of prepared statements. We might try proxsyql later, but that would add more complexity. We could try to reduce the amount of connections but then we'd need telemetry about how much they're idle.. I don't think it's an easy thing to solve.

**Comment by josevalim** [comment] 2019-10-28 16:02
Thanks for the context! Btw, are you using Ecto for those queries?

**Comment by hkrutzer** [comment] 2019-10-28 16:05
Yes, we are.

**Comment by bigardone** [comment] 2019-10-30 06:11
I can confirm that everything is working fine after using the last commit 🎉 Thank you very much for the support guys. 🙌

**Comment by josevalim** [comment] 2019-10-31 09:26
@hkrutzer do you perform 600 deletes and then 600 inserts? Or they are intercalated?

**Comment by hkrutzer** [comment] 2019-10-31 09:35
@josevalim they are sequential, so deletes first then inserts (and in another case, only inserts).

**Comment by josevalim** [comment] 2019-10-31 09:42
@hkrutzer so in your case, we could do delayed closes: we don't close the statement if the next query is the same.

That's what Postgrex does. This requires changing the protocol implementation a bit and we don't have plans for it at the moment. But if you would like to send a PR, we will be happy to review and discuss.

**Comment by iwarshak** [comment] 2024-01-29 16:19
I am actually encountering ER_MAX_PREPARED_STMT_COUNT_REACHED exceptions in my app still. I am on myxql 0.6.4 

This is an an AWS Aurora MySQL database, if that's useful.

**Comment by iwarshak** [comment] 2024-01-29 16:48
@josevalim I am not. From reading the threads related to this issue, it seemed to me that myxql and/or ecto would silently handle this exception. Is this not the case?

**Comment by josevalim** [comment] 2024-01-29 17:00
That may be the case, it has been a while after all. On the other hand, any cache or proxy in the middle may side-step our disconnection. Does the error happen once and then it stops for a while? Also, is it cascading and leading to other failures? Or do you only see a log error (but no exception)?

**Comment by iwarshak** [comment] 2024-01-30 01:46
An exception occurs (shows up in Honeybadger). Once it hits that limit, it seems to cascade to other queries on other nodes even. I have watched the prepared statement count, and it never seems to decrease over time. This makes me think that AWS *is* sidestepping the disconnect.

**Comment by josevalim** [comment] 2024-01-30 09:10
You can confirm this on a new deployment. The prepared statement count should definitely go down, otherwise indeed AWS is getting in the way.

So `prepare: :unnamed` may be the way to go and it is not so uncommon either, it has been our default recommendation for pgbouncer for quite a long time as well.
